In [9]:
import torch

In [3]:
ids = [[12,18,31,45,6,1],
      [1,2,3,4]]

In [4]:
input_ids = torch.tensor(ids) #it will throw error

ValueError: expected sequence of length 6 at dim 1 (got 4)

In [7]:
ids = [[12,18,31,45,6,1],
      [1,2,3,4,0,0]]   #padding

In [8]:
input_ids = torch.tensor(ids) 

#### Problem with self padding(not using attention mask)

In [4]:
from transformers import AutoModelForSequenceClassification
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"

In [27]:
all_ids = torch.tensor([[12,18,31,45,6,1,2500,1000,988,1000],
      [1,2,3,4,1000,2999,0,0,0,0]])
ids_1 = torch.tensor([[12,18,31,45,6,1,2500,1000,988,1000]])
ids_2 = torch.tensor([[1,2,3,4,1000,2999]])

In [21]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

In [28]:
print(model(ids_1).logits)

tensor([[ 1.1564, -1.0404]], grad_fn=<AddmmBackward0>)


In [29]:
print(model(ids_2).logits)

tensor([[ 1.7168, -1.5334]], grad_fn=<AddmmBackward0>)


In [30]:
print(model(all_ids).logits)

tensor([[ 1.1564, -1.0404],
        [ 1.0324, -0.9986]], grad_fn=<AddmmBackward0>)


#### You can see the difference because of just padding by zero thats why we need attention masks 

In [34]:
attention_mask = torch.tensor([[1,1,1,1,1,1,1,1,1,1],
                 [1,1,1,1,1,1,0,0,0,0]])

In [35]:
output = model(all_ids, attention_mask = attention_mask)

In [37]:
output # now getting right output

SequenceClassifierOutput(loss=None, logits=tensor([[ 1.1564, -1.0404],
        [ 1.7168, -1.5334]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

#### Attention mask by default applied if we define padding= True in tokenizer

In [38]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [39]:
sentences = ["I am danish and i love coding.",
            "I love mathematics"]

In [40]:
print(tokenizer(sentences,padding=True))

{'input_ids': [[101, 1045, 2572, 5695, 1998, 1045, 2293, 16861, 1012, 102], [101, 1045, 2293, 5597, 102, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]]}
